### ISSUE TITLE
Escapen van dubbele quotes in Turtle

### ISSUE THREAD

**Issue by companje** [hetutrechtsarchief/MDWS-JSON-to-Turtle#2]
Uitzoeken of dit valide Turtle is. De syntax highlighting van SublimeText vind het niet fijn.

```ttl
rdfs:label "....op herhaling\"" ;
```

**Comment by companje** [comment]
Wellicht een library hiervoor gebruiken zoals [N3](https://www.npmjs.com/package/n3).

**Comment by coret** [comment]
Wellicht ook kijken naar een library als [RocketRML](https://www.npmjs.com/package/rocketrml) waar RML staat voor RDF Mapping Language. Ik heb er geen ervaring mee, maar een belangrijke uitdaging in het project is om meer data elementen in RDF om te zetten (met de juiste types) en daar is RML voor bedoeld.
